AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'pkg/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHeredoc:
  EnforcedStyle: active_support

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'

Style/Documentation:
  Enabled: false
