#!/usr/bin/env ruby

require "del"
require "pathname"

startup_file = Pathname.new(ARGV[0]) if ARGV[0]
Del.start(
  dotenv_file: ENV.fetch("DELRC", Pathname.new(Dir.home).join(".delrc")),
  startup_file: startup_file,
)
